# what do we want
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# How do we want to implement it
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: "/mnt/new_mongo_data"
    type: DirectoryOrCreate