apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  # this defines which pods are going to be represented by this service.
  # The service becomes a network endpoint for either other services 
  # or maybe external users to connect to (eg. browser)
 # selector:
    #app: webapp
    #release: "0" 
    ## releaes: "0-5"
  selector:
    app: activemq
    release: "1"

  ports:
  - name: http
    port: 8161
    nodePort: 30010
    # targetPort: 80
  
  # type: ClusterIP
  type: NodePort