apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    app: activemq
    release: "1"
spec:
  containers:
  - name: activemq
    image:  richardchesterwood/k8s-fleetman-queue:release1-arm64